version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .
      - run:
          name: Run pytest
          command: |
            . venv/bin/activate
            pytest --maxfail=1 --disable-warnings -q

workflows:
  version: 2
  test-workflow:
    jobs:
      - test